parameters:
    neonexus_ionicons.twig.extension.class: NeoNexus\Ionicons\Twig\IoniconsExtension

services:
    neonexus_ionicons.twig.extension:
        class: %neonexus_ionicons.twig.extension.class%
        tags:
            - { name: twig.extension }
